version: '3'

services:
  vehicle-db:
    container_name: vehicle-db
    image: postgres
    environment:
      POSTGRES_DB: "vehicledb"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "123456"
    ports:
      - "5432:5432"
    volumes:
      - my_dbdata:/var/lib/postgresql/data
    networks:
      - vehicle-store-net

  vehicle-db-pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "bolinha@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "123456"
    ports:
      - "6543:80"
    depends_on:
      - vehicle-db
    networks:
      - vehicle-store-net

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - vehicle-store-net

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - vehicle-store-net

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - vehicle-store-net

  mongo:
    image: mongo
    volumes:
      - ./.docker/dbdata:/data/db
      - ./.docker/mongo:/docker-entrypoint-initdb.d
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=VehicleSales
    networks:
      - vehicle-store-net

  consul:
    image: consul
    ports:
      - 8500:8500
    networks:
      - vehicle-store-net

networks:
  vehicle-store-net:
    driver: bridge
volumes:
  my_dbdata: